### ISSUE TITLE
SEO Optimization

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#103]
SEO changes are in two main 'areas'. 1) Static pages (in blog, biz site and main site). These are things like the home page FAQ, Privacy Policy, etc, etc    2) Place Pages (businesses and parks).

1) The document attached below lays out the changes to the static pages. While the attached document covers a lot of ground, in short, the only the changes necessary are those highlighted in green. These deal with the page titles and meta descriptions.

2) Place Pages - The tagging that we'd like to do for place pages is more complicated. In short we need to create tags for:

H1 (Business Name)
Meta Description (First 150 characters of the desc, OR if no description use Name-Category-City-Address)

Other Tags. We'd like to base the place page SEO on Yelp. We'd like the place pages to have other distinct tags for:
Category (e.g. Barynyapp.ca > Walkers and Sitters > Home Stay)
Ratings & Reviews ( e.g. ***\* 4.0 - 4 Reviews)
Address (e.g. 49 Front Street East, Toronto   ON M5E 1B3)

ALSO, we're thinking that if a page has marked their business that they get a special area to enter their own 150 character meta description. We'll just call it Short Description.

So start with the Place pages and think if you want the student to help you do the static pages.

**Comment by glennclarke** [comment]
[BanknYapp-SEO-Page-Audit-03July2016.docx](https://github.com/gudell/bwardp/files/470517/BanknYapp-SEO-Page-Audit-03July2016.docx)

**Comment by zakwhit** [comment]
All meta data has been updated along with structured data for places. Main, blog, and biz sitemaps have been submitted for index in Google Search Console. Will check back to see if places are indexed as required.
