### ISSUE TITLE
Corrections in Vendor Categories

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#114]
Zak, while I was reviewing the file you sent, I found about 30 business that were not categorized properly.  I have attached a file where in the 4th from last column you will see the current category they are listed in and in the 2nd to last column the category they should be in.  Could you please make these changes when you gat a chance.

[Canada Vendors To Change (Aug 13_2016).xlsx](https://github.com/gudell/bwardp/files/418177/Canada.Vendors.To.Change.Aug.13_2016.xlsx)

**Comment by zakwhit** [comment]
Will take care of this during data migration.
