### ISSUE TITLE
Use of member number in profile

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#126]
Zak & Glenn, I am wondering if we can either hide the user number or put a "1" in front, so that we can disguise how many members we currently have.

**Comment by zakwhit** [comment]
I have increased the user ids by a large number. The feed and notification links to other users will be broken. Will be fixed when we do the final data transfer.

**Comment by zakwhit** [comment]
Note: if you were logged in prior to this change you will have to delete your cookies and then log back in.
