### ISSUE TITLE
Problem in City Search Bar - Main Page

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#127]
Zak, this is showing up when I navigate back to the main page.  It was not there the first time

![image](https://cloud.githubusercontent.com/assets/12958622/18255355/f2187ed6-7376-11e6-8dec-afed8f7dd69f.png)

**Comment by gudell** [comment]
Zak, I have cleared my cookies and cached images, but still getting this page.  This also renders the city search useless.  Any ideas?

**Comment by zakwhit** [comment]
I can't seem to replicate this error.

**Comment by gudell** [comment]
Glenn, wasn't getting it on his either, but I have cleared cookies and cache for all parknyapp.com sites and still get it.  We can look at it tomorrow morning

**Comment by gudell** [comment]
fixed by typing in http:// vs www on the sandbox site
