### ISSUE TITLE
City Link Content

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#13]
What content do we want referenced from the "City" links?

**Comment by gudell** [comment]
Similar to 404 page, can we find something fun that a person is linked to.  On that page we need:
- saying we are coming soon
- if t

his is your city and would like us there please email us at (xxx@xxx)

**Comment by melgorka** [comment]
![screen shot 2016-04-18 at 4 44 33 pm](https://cloud.githubusercontent.com/assets/18283781/14608659/ecaebc84-0586-11e6-997f-2fec6404a332.png)

**Comment by zakwhit** [comment]
This is addressed in issue #60
