### ISSUE TITLE
Placeholder Image for "Log in or register to write a review"

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#132]
Where is the image at the left coming from?

**Comment by zakwhit** [comment]
When you log in for the first time a dog photo cookie is set. Whenever you change your dog photo this cookie is changed.

**Comment by gudell** [comment]
Zak, I think the question is why we using the picture we are for the generic user?  What about using the new dog graphic you have or our old one?

**Comment by zakwhit** [comment]
I didn't realize the generic picture was not the default dog image.   It is now the default dog image.
