### ISSUE TITLE
Additional Features - Subscribed Vendor Profile

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#152]
When a vendor marks their profile, in addition to the existing additional 'marked' features they will also get these new features:
- Short (150 Character description to be used as their meta desc
- Multiple photos
- Can see a list of reviews (with hyperlink to the review on the main site)
- Can reply directly to a review as the business
  -Notification of new Reviews
- Can see who has favourited their business (with hyperlink to the user)
- Can enter their hours of operation
- Can indicate which payment types they accept
- Can select a total of 3 categories
- New Mini Dashboard Will show Number of reviews, average rating, rating distribution and number of favourites. User will be able to view the dashboard for this week, this month or this year.

**Comment by gudell** [comment]
Created as separate issues #190, #191, #192, #193, #194, #195, #196, #197, and #198
