### ISSUE TITLE
Period in the location search bar in header

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#158]
A "." is at the beginning of the search area

**Comment by zakwhit** [comment]
Could you screen shot this?

**Comment by gudell** [comment]
![screenshot-www barknyapp com-2016-09-20-21-05-01](https://cloud.githubusercontent.com/assets/12958622/18694203/f8144e5e-7f75-11e6-9875-d54f44d74cf9.png)

Shows up on Safari as well

**Comment by gudell** [comment]
this issue is based on old cookies and fixed
