### ISSUE TITLE
When Marking a Business the business name comes over as "." - See attached 

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#161]
![marking](https://cloud.githubusercontent.com/assets/12958471/18671595/b26eb316-7f12-11e6-9774-9cd9184c7e17.png)

**Comment by glennclarke** [comment]
You get this when you choose to mark a business from the businesses' detail page.

**Comment by gudell** [comment]
This only happens when clicking "mark it" from the User page.  The business name is showing up when you enter this page form the biz site.
