### ISSUE TITLE
Nothing showing with a Pack member

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#163]
I had 2 pack members with a small tile and name. Why is this happening?

**Comment by gudell** [comment]
![screenshot-barknyapp com-2016-09-20-09-21-33](https://cloud.githubusercontent.com/assets/12958622/18671932/04e6e810-7f14-11e6-801e-74ed248dc43e.png)

**Comment by zakwhit** [comment]
User did not exist. I deleted the pack details on these non-existent users.
