### ISSUE TITLE
# of Pack members is wrong

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#165]
Above my profile it says I have 22 Pack Members, but within my Pack I only show 6  Not sure which is right

**Comment by gudell** [comment]
It looks like this may be counting all the "Pending" invites I have out.

**Comment by gudell** [comment]
Second question.  Will these old "Pending" invites now show up as notifications highlighteed in someones header bar?

**Comment by zakwhit** [comment]
I fixed the counts.

Any pending requests will show up in the other person's notifications and if they havent seen it yet the header bell will be highlighted.

**Comment by gudell** [comment]
Zak, the correct number is showing up now.  Not sure why it was different before, but will close this now
