### ISSUE TITLE
Fake members?

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#170]
Zak, I suspect this is a fake member that you set up?

![screenshot-www barknyapp com-2016-09-20-09-43-27](https://cloud.githubusercontent.com/assets/12958622/18672683/0ee1f5f0-7f17-11e6-8c08-1c2f2042b5c5.png)

**Comment by zakwhit** [comment]
Removed.

We should go through the users and remove any other old accounts that were created by sayyeah or testing.
