### ISSUE TITLE
Issues with Paw rating display

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#171]
In some cases the fourth rating is cut off a bit and in others we have 5 paws. 

![screenshot-www barknyapp com-2016-09-20-09-53-21](https://cloud.githubusercontent.com/assets/12958622/18673023/4ae8ef94-7f18-11e6-8129-69f4b79c8848.png)

**Comment by zakwhit** [comment]
I forgot to change the 5 star ratings to 4 star ratings in the database.
Could also be an image caching problem as the old 5 paw rating images have the same file name.

**Comment by gudell** [comment]
still showing the fourth paw being cut off.  Are you seeing this on your browser?  I am using Chrome on Mac
![screenshot-www barknyapp com-2016-09-20-20-41-04](https://cloud.githubusercontent.com/assets/12958622/18693820/cfe5104c-7f72-11e6-9a0a-6b813b4a27bf.png)

**Comment by zakwhit** [comment]
I am not seeing this. I am also not getting the old images.

**Comment by zakwhit** [comment]
I tested on chrome

**Comment by gudell** [comment]
very strange.  so, any suggestions on this?  It can't only be my machine

**Comment by gudell** [comment]
Just looked at Safari and he new pictures are there and paw ratings are fine.  Weird.

**Comment by zakwhit** [comment]
This has to be a caching issue. I checked the image database and the old images don't even exist anymore.

**Comment by gudell** [comment]
ok, did a massive clean out of cookies, including parknyapp and now this is fixed
