### ISSUE TITLE
Appearance of Sub Category filters

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#172]
Sub Category filters only showing up when you select one from the Category search bar.

Here is what I get when I search Listings using a city
![screenshot-www barknyapp com-2016-09-20-10-04-05](https://cloud.githubusercontent.com/assets/12958622/18673401/ac441484-7f19-11e6-85b9-80f4abef78ed.png)
 And here is what I get when I search the Category and select Daycare 
![screenshot-www barknyapp com-2016-09-20-10-06-01](https://cloud.githubusercontent.com/assets/12958622/18673470/efde82c4-7f19-11e6-9864-d4d3f8bd38b0.png)
I think these should be consistent

**Comment by glennclarke** [comment]
I think the rule is once you expand one category they all expand. I'm OK with that.

**Comment by gudell** [comment]
It appears the only way to open the sub categories is by doing a search from the main bar.  If they don't know the sub categories available, then they may never search for something like Waste Disposal under Other Puppy Stuff

**Comment by zakwhit** [comment]
You can see the sub categories by clicking More Filters.

On a search the sub-categories only appear if you have specifically filtered on a sub-category or selected a sub-category in the autocomplete.

**Comment by gudell** [comment]
Yes, completely glossed over that one.  I will add that feature to the email update as well and close this one
