### ISSUE TITLE
Biz search brings error page

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#176]
This is what is returned if I try to search for a business on the biz page
![screenshot-biz barknyapp com-2016-09-20-10-29-42](https://cloud.githubusercontent.com/assets/12958622/18674489/68d79190-7f1d-11e6-9902-2dd7eef6db12.png)

**Comment by zakwhit** [comment]
I am not seeing this error on a search.

There was a bug when a person clicked Next which gave this error which I fixed.

**Comment by gudell** [comment]
It is not happening on Safari, but is happening on my Chrome.  My Chrome seems to hold shit even after I dump the cookies and cache

**Comment by gudell** [comment]
ok, did a massive clean out of cookies, including parknyapp and now this is fixed
