### ISSUE TITLE
New Member Newsfeed

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#177]
I signed up as a new member and I saw the 2 usual welcome type items from Treat. Good.

BUT I also got a bunch of welcome items (e.g.  "Welcome Purina Pawsway to Bark 'n Yapp." Are we supposed to be showing these in the news feed?

ALSO I got a bunch of items that people had done reviews. These people are not in my pack as I don't even have a pack yet. So I'm pretty sure that these should not be showing. See attached.
![review](https://cloud.githubusercontent.com/assets/12958471/18674664/f6f24e98-7f1d-11e6-8069-46d3e714e410.png)

**Comment by zakwhit** [comment]
When we had originally discussed the newsfeed we had agreed to add some nearby reviews and new businesses to the feed.

**Comment by zakwhit** [comment]
The links will be broken however as the old newsfeed items do not reflect the new user ids or place slug... It will work fro new sign-ups however.

**Comment by glennclarke** [comment]
Discussion was to, for now, remove the recent reviews and new business notifications. We'll add this to  separate issue and schedule it for a later date.
