### ISSUE TITLE
Business Accounts having Favorites?

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#182]
Not sure why we have business accounts having favorites.  Zak, do you know what this is tracking, or how/why a business would mark a favorite.  Not sure this should be here.

![screenshot-biz barknyapp com-2016-09-20-21-33-08](https://cloud.githubusercontent.com/assets/12958622/18694664/04efbf9c-7f7a-11e6-9fcd-2a2d32bb7d37.png)

**Comment by zakwhit** [comment]
This tab shows the users that have favourited your business.

**Comment by gudell** [comment]
cool
