### ISSUE TITLE
Business Record - Business Phone and email should be pre-populated

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#187]
We should assume that the phone number and email address used are the ones for the business as well.  We want to try to save businesses as much time as possible

**Comment by zakwhit** [comment]
The idea for having separate email and phone fields is that one set is the Vendor's personal email/phone so that we can contact them directly, and the other set is the public Business phone and email which may be different.

**Comment by zakwhit** [comment]
Just wanted to know if we could close this?

**Comment by glennclarke** [comment]
I'm OK to close this. Galen?

**Comment by gudell** [comment]
In the Personal Contact area, can we say instead of "Phone", "Contact Phone Number"?  I know it is a small change, but it is not entire obvious right now that these may be different numbers
