### ISSUE TITLE
Set Preferred Domain for barknyapp.com

### ISSUE THREAD

**Issue by zakwhit** [gudell/bwardp#189]
This should be done after SSL is implemented.

Are we going to use https://barknyapp.com or https://www.barknyapp.com as preferred domain.  (will prevent duplicates in google searches)

**Comment by glennclarke** [comment]
We'll be using www.barknyapp.com as the preferred domain.

GC

**Comment by gudell** [comment]
Guys has this been completed?

**Comment by zakwhit** [comment]
Hey Galen,

This can be closed.

Thanks,
Zak
