### ISSUE TITLE
Restricted Viewing of Members When Not Logged In

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#20]
When a site visitor is not logged into an account and they want to view a Member, the Member Profile should just show (picture, # of reviews, breed, city, age, & owner).  All other actions should pop up a Sign In page.

**Comment by zakwhit** [comment]
This seems to contradict issue #7 since the see more page takes you to the members page and we are saying in #7 we want that link to take you to the login page.

Let's discuss.

**Comment by glennclarke** [comment]
I don't thnik tha they conflicy, just need clarification.

**Comment by melgorka** [comment]
I think we decided on a recent call that the flow should be. An anonymous visitor clicks on see more, and is taken to the member search page with more members in the area with the filters on top. If they want to see a profile, they click on the image and it prompts them to sign up or log in.
