### ISSUE TITLE
Landing Page - Add Mobile App Links to Web App

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#218]
Remove the "Mobile App Coming Soon" image with App Store Images with links to our mobile app in Google Play and Apple App stores.

**Comment by malhotra-saksham** [comment]
Both App Store and Play Store buttons have been implemented. Need to test on various browsers

**Comment by malhotra-saksham** [comment]
Tested and Reviewed.

**Comment by gudell** [comment]
Covered in #226
