### ISSUE TITLE
Search Results - Add New Parks to Production dB

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#224]
Add the attached file to the production dB 
[Off-Leash Parks Canada Feb 2017.xlsx](https://github.com/gudell/bwardp/files/1265455/Off-Leash.Parks.Canada.Feb.2017.xlsx)

**Comment by Sportster** [comment]
All Off Leash Parks from the "Off-Lease Parks Canada Feb 2017 excel document have been added to the production database

**Comment by gudell** [comment]
@Sportster I see they are there in the app, but if I use the filter "Parks & Attractions" they do not show up. There might be something missing from one of the dB files. Can you please investigate

**Comment by gudell** [comment]
@glennclarke the issue here is in the PlaceKind table.  All the new parks were loaded in with the AttributeID = 1033 and need to be 1007. I have changed 2 of them and they worked. So all the parks in question are from 7254 to 7256 and 7259 to 7476. Once done, we can close this issue

**Comment by gudell** [comment]
Has been updated by @glennclarke and tested by me. All is working fine.
