### ISSUE TITLE
Dog Oriented 404 Page Required

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#24]
We need something designed as a 404 page.  Here is just an idea, but needs more thought
[404 Page.pdf](https://github.com/gudell/bwardp/files/205196/404.Page.pdf)

**Comment by zakwhit** [comment]
404 page linked up. Just waiting on any design recommendations.

**Comment by melgorka** [comment]
The design is good. I would just change the bottom text to something like:

The link might be out of date or missing some text. Go back to the homepage and search for what you're looking for!

**Comment by gudell** [comment]
Here is the suggestion from Glenn and myself:
WOOF! WOOF!
YOU'RE DIGGING IN THE WRONG SPOT
Then and link to take them back to the search area
