### ISSUE TITLE
Search from Main Landing Page

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#3]
First search box within picture requires a city, otherwise it brings back no results

**Comment by gudell** [comment]
Some terms work and some terms do not.  If I type in "Groomer" I end up getting a 504 Gateway timeout after spinning for about 1 minute

**Comment by zakwhit** [comment]
These seems to be working most of the time however I do find instances where a search that previously brought up results comes back with no results. This needs to be revisited.
