### ISSUE TITLE
Business Search Behaviour from Magnifying Glass

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#38]
We should look at making the magnifying glass work as a "go search now" button. Or discuss.

**Comment by melgorka** [comment]
Can you share a bit more detail on what you're thinking here? That it can search any content on the site? Or is this specifically to the blog. Thanks!

**Comment by glennclarke** [comment]
JUst that I've caught myself hitting the magnifying glass to beginf hte search (after typing search content)

**Comment by gudell** [comment]
If you click on the magnifying glass it opens a box for name and city.  If you type in a business name and city and then press the magnifying glass to search, it just closes the name and city boxes.  This should run the search as it would when you press enter.
