### ISSUE TITLE
Upvote down vote icons

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#39]
The arrow buttons for changing the pages of boxes/posts on the trending section are not a perfect circle. What is shown is an arrow in a circle and the top of the circle is flat as if it is partially cut off. This remains consistent when I change the page to go to the next set of posts or boxes.

**Comment by zakwhit** [comment]
I do not see this in Windows Chrome or Edge. It looks a little flat on top but this design is coming from a custom font-family that comes with the slider library.
