### ISSUE TITLE
Mark your Business Flow

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#51]
We need to review the flow of this page. It seems to me that we don't give the user enough chance or the right place to say "OK, so I can't find my business now it want to create it from scratch."

**Comment by gudell** [comment]
Need to discuss current flow and determine if we need to make enhancements

**Comment by glennclarke** [comment]
Zak, I'm sure that implementing elastic search in the business search will improve this issue, none the less lets have a quick chat before actioning this one.
