### ISSUE TITLE
Wording Changes - Main landing page

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#52]
I've sent email to Zak with the changes.
![screen shot 2016-04-21 at 10 54 46 am](https://cloud.githubusercontent.com/assets/12958471/15018664/92304598-11e8-11e6-9f7b-6cfcc606fca4.png)

**Comment by gudell** [comment]
Zak, the black text on the main picture is very difficult to see.  I think we will need a different color of font, or we may need to create a shadow box under the text.

Thanks….

Galen Udell | Founder & Top Dog | 
www.barknyapp.com http://www.barknyapp.com/ - Dog’s Best Friend
Phone: 416-434-9255
galen@barknyapp.com mailto:galen@barknyapp.com
