### ISSUE TITLE
Link from Vendor Address Missing

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#6]
There should be a link on Vendor address to pin on Map Page

**Comment by zakwhit** [comment]
Let's discuss again exactly where we want this link to go. 

In my opinion the best place for this link to go would be a single business view on the map page. This would take some time to implement since currently if someone moved that map view all surrounding businesses would pop up.

**Comment by melgorka** [comment]
I'm fine with it either going to a single business view on the map page or to the vendor listing itself.

**Comment by gudell** [comment]
Let's keep as is and test with users during MVP
