### ISSUE TITLE
User Profile Page - Age says "Invalid date old" when no birthdate is supplied

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#62]

**Comment by glennclarke** [comment]
I checked an existing member profile and the error is still there. Do I need to create a new profile to see the correction?

**Comment by zakwhit** [comment]
Could you provide a link to an example of this?

**Comment by glennclarke** [comment]
I can't find the account where I saw this. I'll try again when the data load is complete. Will close fore now.

**Comment by zakwhit** [comment]
I found one and it was because their birthday was entered in as 0000-00-00.

Set it to NULL.

Thanks,
Zak
