### ISSUE TITLE
# of Listing in the "Best of"?

### ISSUE THREAD

**Issue by gudell** [gudell/bwardp#8]
Currently we have only 4. I thought we were making page references below any Vendor list, so that someone could jump from page 1 to say page 5?

**Comment by gudell** [comment]
We will change the text below the 4 listings to refer someone to the the map to search more

**Comment by zakwhit** [comment]
Added see more button to landing page. Listings show 5 results now instead of 4.  Will leave numbered page links to future version.

To keep with the "Best Of" algorithm the see more link must go to the Listing page, not the map.
