### ISSUE TITLE
Landing page search

### ISSUE THREAD

**Issue by melgorka** [gudell/bwardp#80]
When you search business type: groomer and city (Hamilton), it takes you to the right results on the map page but doesn't check off the groomer category on the filters. (I didn't try all categories just groomer).

**Comment by zakwhit** [comment]
I'm not sure I understand this. Why does the landing search take you to the map page?  Are you typing groomer in the left field?

**Comment by zakwhit** [comment]
Unfortunately, typing a category in the input field will not mark it in the categories filter.

**Comment by gudell** [comment]
Need to revisit the whole process of searching to make sure that people can find what they are looking for and not think that we have limited data in their region of search

**Comment by gudell** [comment]
same as #93
