### ISSUE TITLE
Install Site Monitoring Tools

### ISSUE THREAD

**Issue by glennclarke** [gudell/bwardp#91]
Use a service to monitor the site. Send MS ,email etc when site down.

ALSO make sure GC knows how to restart elements of the site.

**Comment by zakwhit** [comment]
Set up monitors on four various pages using Uptime Robot: barknyapp.com, biz.barknyapp.com, blog.barknyapp.com, barknyapp.com/listing. Glenn and I will be emailed by the bot if the site goes down.
